name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动运行一次
  workflow_dispatch:     # 支持网页端手动点击触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Fork
        uses: tgymnich/fork-sync@v1.8.0
        with:
          owner: byJoey             # 原作者账号（如果同步 BPB-Wizard 则改为 bia-pain-bache）
          repo: cfnew               # 原作者仓库名（如果同步 BPB-Wizard 则改为 BPB-Wizard）
          base: main                # 原作者分支
          head: main                # 你的分支
